// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	CategoryID   int64  `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
	CategoryName string `gorm:"column:category_name" json:"category_name"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
