// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrdertab = "ordertabs"

// Ordertab mapped from table <ordertabs>
type Ordertab struct {
	OrderID int64 `gorm:"column:order_id;primaryKey;autoIncrement:true" json:"order_id"`
	UserID  int64 `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName Ordertab's table name
func (*Ordertab) TableName() string {
	return TableNameOrdertab
}
