// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ProductID    int64  `gorm:"column:product_id;primaryKey;autoIncrement:true" json:"product_id"`
	ProductName  string `gorm:"column:product_name" json:"product_name"`
	Price        int32  `gorm:"column:price" json:"price"`
	NumInventory int32  `gorm:"column:num_inventory" json:"num_inventory"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
