// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductCategory = "product_category"

// ProductCategory mapped from table <product_category>
type ProductCategory struct {
	ProductID  int64 `gorm:"column:product_id;primaryKey;autoIncrement:true" json:"product_id"`
	CategoryID int64 `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
}

// TableName ProductCategory's table name
func (*ProductCategory) TableName() string {
	return TableNameProductCategory
}
