// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	CategoryID   int64
	CategoryName string
	Products     []*Product `gorm:"many2many:product_category;"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
