// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderDetail = "order_detail"

// OrderDetail mapped from table <order_detail>
type OrderDetail struct {
	OrderID   int64 `gorm:"column:order_id;primaryKey" json:"order_id"`
	ProductID int64 `gorm:"column:product_id;primaryKey" json:"product_id"`
}

// TableName OrderDetail's table name
func (*OrderDetail) TableName() string {
	return TableNameOrderDetail
}
